"""Liste der gängigen Filament-Hersteller für Dropdown-Auswahl."""

FILAMENT_MANUFACTURERS = [
    "Bambu Lab",
    "Polymaker",
    "Prusament",
    "eSun",
    "Sunlu",
    "Geeetech",
    "Overture",
    "Elegoo",
    "Anycubic",
    "Creality",
    "Hatchbox",
    "ColorFabb",
    "Fillamentum",
    "MatterHackers",
    "Inland",
    "3D Solutech",
    "AmazonBasics",
    "Eryone",
    "Atomic Filament",
    "Verbatim",
    "Extrudr",
    "Das Filament",
    "Spectrum",
    "FormFutura",
    "Real Filament",
]
